name: ベンチマーク

run-name: ${{ inputs.function_benchmarks }}

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "Minecraft version"
        required: false
        default: "release"
      warmup_iterations:
        type: number
        description: "Number of warmup iterations"
        required: false
        default: 5
      measurement_iterations:
        type: number
        description: "Number of measurement iterations"
        required: false
        default: 5
      time:
        type: number
        description: "Duration of iterations in seconds"
        required: false
        default: 10
      forks:
        type: number
        description: "Number of forks"
        required: false
        default: 5
      time_unit:
        type: choice
        description: "Output time unit"
        required: false
        default: us
        options: [ ns, us, ms, s, m ]
      mc_args:
        type: string
        description: "Minecraft arguments to use with forks"
        required: false
        default: "nogui"
      function_benchmarks:
        type: string
        description: "Data pack names for function benchmark"
        required: false
        default: ""

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: チェックアウト
        uses: actions/checkout@v3
      - name: Javaのセットアップ
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Minecraftのセットアップ
        id: minecraft
        uses: mcenv/setup-minecraft@v3
        with:
          version: ${{ inputs.version }}
      - name: ベンチマーク
        run: |
          cd 11_benchmark/actions
          curl -L -o mch.jar https://github.com/mcenv/mch/releases/download/v0.15.0/mch.jar
          java -jar mch.jar --mc=$MINECRAFT --warmup_iterations=${{ inputs.warmup_iterations }} --measurement_iterations=${{ inputs.measurement_iterations }} --time=${{ inputs.time }} --forks=${{ inputs.forks }} --time_unit=${{ inputs.time_unit }} --mc_args=${{ inputs.mc_args }} --function_benchmarks=${{ inputs.function_benchmarks }}
      - name: ベンチマーク結果のアップロード
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.minecraft.outputs.version }}
          if-no-files-found: error
          path: |
            11_benchmark/actions/mch-results.json
            11_benchmark/actions/mch-results.md
      - uses: actions/github-script@v6
        with:
          script: |
            require('./11_benchmark/actions/benchmark.js')({ context });
